module3-task1-1
ezhuikova/1018265-mishka-16 pull request #4
Opened 2019-04-09 14:41 UTC by ezhuikova

2019-04-09 21:18 UTC, KelvinOm requested changes

2019-04-09 21:18 UTC, KelvinOm commented on source/sass/variables.scss
> +$font: normal normal normal 15px/1.2 "OpenSans";
Правильно так
$font: "Open Sans", "Arial", sans-serif;

2019-04-09 21:18 UTC, KelvinOm commented on source/sass/scaffolding.scss
> +  width: 100%;
Зачем это тут?
 ```
height: 100%;
 width: 100%;
```

2019-04-09 21:18 UTC, KelvinOm commented on source/index.html
>      <ul class="main-nav__list site-list">
Для этого надо добавить стили

2019-04-09 21:18 UTC, KelvinOm commented on source/index.html
>    <a class="page-header__logo" href="/">
Логотип должен быть по центру. Текущую реализацию центрирования оставить кнопку разместить через абсолют чтобы не мешала.

2019-04-09 21:18 UTC, KelvinOm commented on source/index.html
>        <h2 class="weekly-good__title">Вязаные корзинки</h2>
не вижу чтобы были стилизованы шрифты.
и нет стилей для visually-hidden

2019-04-09 21:18 UTC, KelvinOm commented on source/sass/blocks/index/weekly-good.scss
> +  height: 315px;
width: auto; -> width: 100%;
height: 315px; -> height: auto;

2019-04-09 21:18 UTC, KelvinOm commented on source/sass/blocks/index/weekly-good.scss
> +  height: 315px;
Заход на будущую адаптивность

2019-04-09 21:18 UTC, KelvinOm commented on source/sass/blocks/shared/about_company.scss
> +  color: $seafoam-blue;
(минор) color -> fill это все таки svg

2019-04-09 21:18 UTC, KelvinOm commented on source/index.html
> +        <a class="social__link social__link--instagram" href="https://www.instagram.com/htmlacademy">
а почему иконки синие?

2019-04-09 21:18 UTC, KelvinOm commented on source/index.html
> +        <a class="social__link social__link--instagram" href="https://www.instagram.com/htmlacademy">
![2019-04-10_00-16-59](https://user-images.githubusercontent.com/11555074/55836015-fabb3080-5b25-11e9-98b3-7dc37b47b59e.png)

2019-04-11 13:15 UTC, KelvinOm requested changes

2019-04-11 13:15 UTC, KelvinOm commented on source/index.html
>        <li class="categories__item categories__item--interior">
По всей этой области должна быть возможность кликнуть.
Ховеры бы еще добавить.

2019-04-11 13:15 UTC, KelvinOm commented on source/index.html
> +  <section class="weekly-good container">
container — like

2019-04-11 13:15 UTC, KelvinOm commented on source/sass/blocks/shared/container.scss
> +  padding: 0 $margin;
Тут хорошо бы и padding-top и padding-bottom добавить. Они во всех контейнерах должны быть одинаковые.

2019-04-11 13:15 UTC, KelvinOm commented on source/sass/blocks/shared/page-header.scss
> +  min-height: 79px;
`align-items: center;` и `min-height: 79px;`  не дружат в ИЕ.

2019-04-11 13:15 UTC, KelvinOm commented on source/index.html
> +          <use href="symbol-defs.svg#icon-icon-feature-money"></use>
А что это за штука просвети. Оно кросбараузерно? В ИЕ сейчас не работает.

2019-04-11 13:15 UTC, KelvinOm commented on source/index.html
> +    <svg class="copyright__text-svg copyright__text-svg--academy icon">
![2019-04-11_16-05-43](https://user-images.githubusercontent.com/11555074/55960097-c30ece80-5c74-11e9-9c5f-9f757a2bf900.png)

2019-04-11 13:15 UTC, KelvinOm commented on source/index.html
> +    <svg class="copyright__text-svg copyright__text-svg--academy icon">
Все еще не правильный цвет.

2019-04-11 13:15 UTC, KelvinOm commented on source/sass/blocks/index/categories.scss
> +  display: flex;
Пожалуйста ознакомься http://codeguide.academy/html-css.html#css-order

2019-04-12 09:19 UTC, ezhuikova commented on source/sass/blocks/shared/container.scss
> +  padding: 0 $margin;
padding: 0 $margin; - вот тут как раз указан padding-top и padding-bottom 
В variables.scss - $margin: 30px

2019-04-13 18:36 UTC, KelvinOm requested changes

2019-04-13 18:36 UTC, KelvinOm commented on source/sass/blocks/index/categories.scss
> +  background-size: auto;
(минор) лучше cover

2019-04-13 18:38 UTC, KelvinOm commented on source/sass/blocks/shared/container.scss
> +  padding: 0 $margin;
padding: 0 $margin = padding-top: 0, padding-right: 30px, padding-bottom: 0, padding-left: 30px;

Top и bottom тоже нужны

2019-04-13 18:42 UTC, KelvinOm commented on source/index.html
>        <li class="categories__item categories__item--interior">
Все еще ссылка покрывает не всю область и нужен атрибут href="#"

2019-04-15 08:43 UTC, KelvinOm requested changes

2019-04-15 08:43 UTC, KelvinOm commented on source/index.html
> +          <span>Каталог товаров</span></a>
(минор)
 ```
<a class="site-list__link" href="catalog.html">
          <span>Каталог товаров</span>
</a>
```

2019-04-15 08:43 UTC, KelvinOm commented on source/sass/blocks/index/categories.scss
> +  margin-top: -17px;
Выглядит как фикс через костыль :) Мб как-то по другому можно?

2019-04-15 08:43 UTC, KelvinOm commented on source/sass/blocks/index/categories.scss
> +  a {
Тут лучше через класс. Селектор через тег можно использовать только в крайних случаях. Это точно не он.

2019-04-15 08:43 UTC, KelvinOm commented on source/sass/blocks/index/categories.scss
> +  &:hover {
like! Хорошее решение!

2019-04-15 16:39 UTC, merged