Modue3 task1 catalog
ezhuikova/1018265-mishka-16 pull request #5
Opened 2019-04-14 13:44 UTC by ezhuikova

2019-04-14 19:11 UTC, KelvinOm commented
![hover](https://user-images.githubusercontent.com/11555074/56097833-13e72700-5f02-11e9-887a-2c9f39dd892d.gif)

Тут контент не должен сдвигаться вниз. Эти плашки должны как бы приподниматься. Сама попробуешь реализовать?

2019-04-14 19:16 UTC, KelvinOm commented on source/catalog.html
> +        <a class="site-list__link" href="catalog.html"><i></i>
Отступы лучше делать через модификаторы на соответствующих элементах.
Еще можно сделать у всех ссылок одинаковые отступы, а иконки абсолютно позиционировать.

2019-04-14 19:16 UTC, KelvinOm commented on source/catalog.html
> +             alt="Зайчик-попрыгайчик">
не надо переносить атрибуты, линт нас не похвалит.

2019-04-14 19:16 UTC, KelvinOm commented on source/catalog.html
> +             alt="Зайчик-попрыгайчик">
и далее тоже

2019-04-14 19:16 UTC, KelvinOm commented on source/catalog.html
> +          <h3 class="catalog__item-title">Зайчик-попрыгайчик</h3>
h3 -> a

2019-04-14 19:17 UTC, KelvinOm commented
Катерина, прогони, пожалуйста, npm test в обоих ПР, есть ошибки.

2019-04-15 06:35 UTC, ezhuikova commented on source/catalog.html
> +             alt="Зайчик-попрыгайчик">
Шторм форматирует (для работы так настроен). Буду ручками переносить (

2019-04-15 08:35 UTC, KelvinOm requested changes

2019-04-15 08:35 UTC, KelvinOm commented on source/catalog.html
> +        <div class="catalog__item-description-wrapper">
(минор)
catalog__item-description-wrapper
catalog__item-description
catalog__item-price
...

Тут везде можно item убрать, селекторы будут проще и понятнее.

2019-04-15 08:35 UTC, KelvinOm commented on source/catalog.html
> +        <img class="catalog__image" src="img/photo-hare-mobile@1x.jpg" width="260" height="195" alt="Зайчик-попрыгайчик">
Сорян, сразу не увидел. Но 

1) картинка должна быть обернута в ссылку
2) Картинка должна быть `display: block;`, тогда тебе не надо будет писать  у `catalog__item-description-wrapper` `margin-top: -6px;`. Этот отступ добавляется так как картинка по умолчанию инлайновый элемент.

2019-04-15 16:39 UTC, merged