Module4 task1 header
ezhuikova/1018265-mishka-16 pull request #7
Opened 2019-04-23 19:49 UTC by ezhuikova

2019-04-24 19:59 UTC, KelvinOm commented
Основная сложность в верстке шапки это "Вязание на заказ" и "Каталог товаров". Просто закомментируй их и сделай красивую верстку. Потом через position: absolute, выдерних их из потока и аккуратно поставь в правильное место.

2019-04-24 20:00 UTC, KelvinOm requested changes

2019-04-24 20:00 UTC, KelvinOm commented on source/index.html
>    <div class="page-header__wrapper">
А почему wrapper пустой оказался?

2019-04-24 20:00 UTC, KelvinOm commented on source/sass/blocks/shared/main-nav.scss
> +  top: 32px;
Зачем, поменяла? Раньше было гибче.

2019-04-24 20:00 UTC, KelvinOm commented on source/sass/blocks/shared/page-header.scss
> +  display: none;
Зачем нам все эти стили если мы не показываем этот элемент на мобилке?
```
  position: absolute;
  top: 107px;
  right: 51px;
  font-size: 15px;
  line-height: 24px;
  letter-spacing: normal;
  text-align: right;
  color: $gray-color;
```
Мб перенесем в @media (min-width: $tablet-width)

2019-04-24 20:00 UTC, KelvinOm commented on source/sass/blocks/shared/page-header.scss
> +    img {
Почему это тут?

2019-04-24 20:00 UTC, KelvinOm commented on source/sass/blocks/shared/site-list.scss
> +      margin-left: calc(100% - (316px + 84px + 2px));
Зачем так сложно? 

![2019-04-24_22-52-31](https://user-images.githubusercontent.com/11555074/56689456-c88ffe00-66e3-11e9-9b13-311057d81524.png)

Сделай так чтобы красный блок тянулся и толкал остальные два.

2019-04-24 20:00 UTC, KelvinOm commented on source/sass/blocks/shared/site-list.scss
> +    min-height: 88px;
Тебе не надо задавать высоту для ссылок и выравнивать текст паддингами.
1) Кликабельной должна быть только часть с текстом.
2) Выравнивай ссылки внутри контейнеров с помощью flex

2019-04-24 20:00 UTC, KelvinOm commented on source/index.html
>            <span>Каталог товаров</span>
Зачем эти спаны? Их можно удалить

2019-04-27 17:15 UTC, KelvinOm requested changes

2019-04-27 17:15 UTC, KelvinOm commented on source/index.html
> +          <span>Новые поступления</span>
Спаны зачем в site-list__item?

2019-04-27 17:15 UTC, KelvinOm commented on source/index.html
> +    <div class="categories__footer"></div>
Зачем этот див? Нужно стараться избегать лишних контейнеров и пустых элементов на странице, если это чем-то не обосновано.

2019-04-27 17:15 UTC, KelvinOm commented on source/index.html
> +           alt="Вязаные корзинки">
В рамках этого проекта не надо переносить атрибуты.

2019-04-27 17:15 UTC, KelvinOm commented on source/index.html
> +      <a href="cart.html" class="weekly-good__order button" type="button">Заказать</a>
у ссылок не бывает атрибута type="button"

2019-04-27 17:15 UTC, KelvinOm commented on source/index.html
>          <i>
Тег i тут зачем?

2019-04-27 17:15 UTC, KelvinOm commented on source/sass/blocks/index/categories.scss
> +    background-image: url("../../../img/bg-zigzag-fill.svg");
Лучше использовать абсолютные пути `/img/bg-zigzag-fill.svg`. Это гибче, куда бы ты не перенесла файл или еще что-то у тебя все будет хорошо.

2019-04-27 17:15 UTC, KelvinOm commented on source/sass/blocks/index/weekly-good.scss
> +    //min-height: 80px;
Закомментированного кода быть не должно.

2019-04-27 17:15 UTC, KelvinOm commented on source/sass/blocks/shared/site-list.scss
> +      span {
Это точно нужно? В БЭМ следует избегать такого стиля.

2019-04-27 17:15 UTC, KelvinOm commented on source/sass/variables.scss
> +$tablet-width: 772px;
Хорошо бы еще минимальную ширину для мобилки добавить.

![2019-04-27_19-54-06](https://user-images.githubusercontent.com/11555074/56852634-3c214d80-6926-11e9-969d-29d849f85685.png)

2019-04-27 17:15 UTC, KelvinOm commented on source/index.html
> +  <a class="page-header__logo" href="/">
Кликабельным должен быть только логотип.

![2019-04-27_19-55-20](https://user-images.githubusercontent.com/11555074/56852644-66730b00-6926-11e9-97f4-7598085e2be7.png)

2019-04-29 20:44 UTC, KelvinOm requested changes

2019-04-29 20:44 UTC, KelvinOm commented on source/index.html
> +    <ul class="main-nav__list site-list">
А зачем второй такой же блок? Почему не вытащить эти два пункта из исходного main-nav__list

2019-04-29 20:44 UTC, KelvinOm commented on source/sass/blocks/shared/site-list.scss
> +  height: 79px;
От высоты не получилось избавиться?

2019-04-29 20:44 UTC, KelvinOm commented on source/sass/blocks/shared/page-header.scss
> +  //  display: flex;
Закомментированного кода быть не должно

2019-04-29 20:44 UTC, KelvinOm commented on source/index.html
> +    <a class="copyright__link" href="http://htmlacademy.ru">
Ховера не хватает.

2019-04-29 20:44 UTC, KelvinOm commented on source/index.html
> +        </a>
1) Ховера не хватает
2) `<a class="site-list__link" href="catalog.html">Новые поступления</a>`. Другие теги тоже надо поправить

2019-04-30 11:01 UTC, ezhuikova commented on source/sass/blocks/shared/site-list.scss
> +  height: 79px;
для мобильной версии это высота пункта меню

2019-05-02 05:03 UTC, ezhuikova commented on source/index.html
>          <i>
У всех иконок разные размеры, я обернула их в тег i с заданной высотой и выровняла по центру - так они соотвеnствуют макету и описание не скачет

2019-05-02 05:19 UTC, merged