Module4 task1 catalog without header
ezhuikova/1018265-mishka-16 pull request #8
Opened 2019-04-27 19:07 UTC by ezhuikova

2019-04-29 21:08 UTC, KelvinOm requested changes

2019-04-29 21:08 UTC, KelvinOm commented on source/catalog.html
> +    <div class="page-main__footer"></div>
Псевдоэлемент?

2019-04-29 21:08 UTC, KelvinOm commented on source/catalog.html
> +            <source srcset="img/photo-toys-desktop@1x.jpg" media="(min-width: 1150px)">
а как же ретина?

2019-04-29 21:08 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    height: 659px;
Катерина, надо все проверить и учитывать переполнение проверить. 

Попробуй сделать так и посмотри что получится:
![2019-04-29_23-58-21](https://user-images.githubusercontent.com/11555074/56926957-94e61700-6adb-11e9-806c-30988bff1bc6.png)

И еще попробуй добавить 4 блок, он должен переносится на другую сроку и ничего не ломать

2019-05-01 13:38 UTC, KelvinOm requested changes

2019-05-01 13:38 UTC, KelvinOm commented on source/catalog.html
> +          <picture class="catalog__image">
Не надо работать с тегом picture, для тебя его нет. Работай, пожалуйста, с img.

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    flex: 50%;
flex-basis: 50%;

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    flex: 1 1 100%;
flex-grow: 1;

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    flex: 60%;
flex-basis: auto;

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    height: 100%;
высоту для картинки в tablet надо сделать 100%, а ширину auto;

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    overflow: hidden;
это надо повесить непосредственно на ссылку

2019-05-01 13:38 UTC, KelvinOm commented on source/catalog.html
> +          <picture class="catalog__image">
ИЕ с этим плохо справляется. 

![2019-05-01_16-04-07 (2)](https://user-images.githubusercontent.com/11555074/57018151-eea92700-6c2a-11e9-8c14-3118d9a20b04.png)

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    margin-bottom: 52px;
Теперь между контейнером каталога и футтером слишком большой отступ получился.

2019-05-01 13:38 UTC, KelvinOm commented on source/sass/blocks/catalog/catalog.scss
> +    min-height: 659px;
Тут тебе это точно не нужно, надо заставить контент тянуться за счет контента.

2019-05-01 13:38 UTC, KelvinOm commented on source/catalog.html
> +          <picture class="catalog__image" >
Катерина, чтобы picture заработала в ИЕ надо подключить полифил, например так:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/picturefill/3.0.3/picturefill.js"></script>
```

2019-05-01 13:46 UTC, KelvinOm commented
Катерина, перед отправкой ПРа неоходимо проверять то, что получилось. Такие ошибки легко отловить.

Есть такая штука, называется self review. Т.е. перед тем как отправить ПР, надо отвлечься и отдохнуть, потом посмотреть свою работу, сделать правки если надо и тогда уже отправлять ПР.

![2019-05-01_16-40-40](https://user-images.githubusercontent.com/11555074/57019736-ff0fd080-6c2f-11e9-9baf-b60f40ec8aad.png)
![2019-05-01_16-40-29](https://user-images.githubusercontent.com/11555074/57019738-ff0fd080-6c2f-11e9-9483-66ad395d4de3.png)
![2019-05-01_16-40-02](https://user-images.githubusercontent.com/11555074/57019739-ff0fd080-6c2f-11e9-950a-10717bc7847a.png)

2019-05-02 19:04 UTC, ezhuikova commented on source/sass/blocks/catalog/catalog.scss
> +    overflow: hidden;
overflow: hidden; ты имеешь ввиду?  Не поняла

2019-05-02 19:54 UTC, merged